# Generated by Django 3.0.11 on 2020-11-22 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 22, 11, 33, 28, 575452)),
        ),
    ]
