# Generated by Django 3.1.4 on 2020-12-05 13:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='signed_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='signed_event', to=settings.AUTH_USER_MODEL),
        ),
    ]
