# Generated by Django 3.0.10 on 2020-11-22 13:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partee', '0002_auto_20201122_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='party',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 22, 14, 10, 59, 545896)),
        ),
    ]
